// Libraries
using UnityEngine;

public class Shoot: MonoBehaviour
{
    // Variables
    // Velocity applied to the projectile when fired
    [Header("Shoot Settings")]
    [SerializeField] private Vector2 initialShotVelocity = Vector2.zero;
    // Projectile spawn points and prefab
    [Header("Projectile Settings")]
    [SerializeField] private Transform spawnPointRight;
    [SerializeField] private Transform spawnPointLeft;
    [SerializeField] private Projectile projectilePrefab;

    // Component Refs
    private SpriteRenderer sr;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        // Get the SpriteRenderer component
        sr = GetComponent<SpriteRenderer>();
        // Error Checking
        if (initialShotVelocity == Vector2.zero)
        {
            // Set a default value for initialShotVelocity
            initialShotVelocity = new Vector2(10f, 0f);
            // Log a warning if it was not set
            Debug.LogError("Shoot: initialShotVelocity is not set.");
        }
        // Check if spawn points and projectile prefab are set
        if (spawnPointLeft == null || spawnPointRight == null || projectilePrefab == null)
        {
            // Log an error if any are not set
            Debug.LogError("Shoot: Spawn points or projectile is not set on Shoot component of ");
        }
    }

    // Method to fire a projectile
    public void Fire()
    {
        // Instantiate the projectile at the appropriate spawn point based on the sprite's facing direction
        Projectile curProjectile;
        // If not flipped, shoot to the right
        if (!sr.flipX)
        {
            // Instantiate projectile at right spawn point
            curProjectile = Instantiate(projectilePrefab, spawnPointRight.position, Quaternion.identity);
            // Set its velocity to the initial shot velocity
            curProjectile.SetVelocity(initialShotVelocity);
            // Set its spin direction to clockwise
            curProjectile.SetSpinDirection(false);
        }
        // If flipped, shoot to the left
        else
        {
            // Instantiate projectile at left spawn point
            curProjectile = Instantiate(projectilePrefab, spawnPointLeft.position, Quaternion.identity);
            // Set its velocity to the negative initial shot velocity on the x-axis
            curProjectile.SetVelocity(new Vector2(-initialShotVelocity.x, initialShotVelocity.y));
            // Set its spin direction to counter-clockwise
            curProjectile.SetSpinDirection(true);
        }


    }

    public void FireLeft()
    {
        // Instantiate the projectile at the appropriate spawn point based on the sprite's facing direction
        Projectile curProjectile;
        
        if (sr.flipX)
        {
            //// Instantiate projectile at left spawn point
            //curProjectile = Instantiate(projectilePrefab, spawnPointLeft.position, Quaternion.identity);
            //// Set its velocity to the negative initial shot velocity on the x-axis
            //curProjectile.SetVelocity(new Vector2(-initialShotVelocity.x, initialShotVelocity.y));
            //// Set its spin direction to counter-clockwise
            //curProjectile.SetSpinDirection(true);

            // Instantiate projectile at right spawn point
            curProjectile = Instantiate(projectilePrefab, spawnPointRight.position, Quaternion.identity);
            // Set its velocity to the initial shot velocity
            curProjectile.SetVelocity(initialShotVelocity);
            // Set its spin direction to clockwise
            curProjectile.SetSpinDirection(false);
        }
        
        else
        {
            //// Instantiate projectile at right spawn point
            //curProjectile = Instantiate(projectilePrefab, spawnPointRight.position, Quaternion.identity);
            //// Set its velocity to the initial shot velocity
            //curProjectile.SetVelocity(initialShotVelocity);
            //// Set its spin direction to clockwise
            //curProjectile.SetSpinDirection(false);

            // Instantiate projectile at left spawn point
            curProjectile = Instantiate(projectilePrefab, spawnPointLeft.position, Quaternion.identity);
            // Set its velocity to the negative initial shot velocity on the x-axis
            curProjectile.SetVelocity(new Vector2(-initialShotVelocity.x, initialShotVelocity.y));
            // Set its spin direction to counter-clockwise
            curProjectile.SetSpinDirection(true);
        }


    }

    // Update is called once per frame
    void Update()
    {

    }
}
